apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: watchn-orders
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Vivek7964/microservice-demo.git
    targetRevision: master
    path: src/orders/chart
    helm:
      releaseName: orders
      parameters:
        - name: image.tag
          value: v1
        - name: messaging.activemq.brokerUrl
          value: tcp://activemq-0.activemq:61616
  destination:
    server: https://kubernetes.default.svc
    namespace: watchn
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
