apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: watchn-ui
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Vivek7964/microservice-demo.git
    targetRevision: master
    path: src/ui/chart
    helm:
      releaseName: ui
      parameters:
        - name: image.tag
          value: v1
  destination:
    server: https://kubernetes.default.svc
    namespace: watchn
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
