apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: watchn
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Vivek7964/microservice-demo.git
    targetRevision: master
    path: deploy/kubernetes

  destination:
    server: https://kubernetes.default.svc
    namespace: watchn

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true