apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: watchn
  namespace: logging
spec:
  version: 9.2.0
  count: 1

  elasticsearchRef:
    name: watchn

  podTemplate:
    spec:
      containers:
        - name: kibana
          resources:
            requests:
              cpu: 200m
              memory: 768Mi
            limits:
              cpu: 1000m
              memory: 1Gi