grafana:
  enabled: true

  replicas: 1

  resources:
    requests:
      cpu: 50m
      memory: 192Mi
    limits:
      cpu: 300m
      memory: 384Mi

  readinessProbe:
    initialDelaySeconds: 30
    timeoutSeconds: 5
    periodSeconds: 10
    failureThreshold: 12

  livenessProbe:
    initialDelaySeconds: 120
    timeoutSeconds: 5
    periodSeconds: 10
    failureThreshold: 6

  service:
    type: ClusterIP

  persistence:
    enabled: false

prometheus:
  enabled: true

  prometheusSpec:
    replicas: 1

    retention: 3d

    resources:
      requests:
        cpu: 75m
        memory: 192Mi
      limits:
        cpu: 300m
        memory: 384Mi

    storageSpec: {}

alertmanager:
  enabled: true

  alertmanagerSpec:
    replicas: 1

    resources:
      requests:
        cpu: 25m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi

prometheusOperator:
  enabled: true

  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

kube-state-metrics:
  enabled: true

  resources:
    requests:
      cpu: 20m
      memory: 48Mi
    limits:
      cpu: 100m
      memory: 96Mi

prometheus-node-exporter:
  enabled: true

  resources:
    requests:
      cpu: 20m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 64Mi