apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: watchn-ui-route
  namespace: watchn
spec:
  parentRefs:
    - name: watchn-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: ui
          port: 80
