services:
  ui:
    ports:
      - "80:8080"
    environment:
    - JAVA_OPTS=-XX:MaxRAMPercentage=75.0 -Djava.security.egd=file:/dev/urandom
    - SERVER_TOMCAT_ACCESSLOG_ENABLED=true
    - ENDPOINTS_CATALOG=http://catalog:8080
    - ENDPOINTS_CARTS=http://carts:8080
    - ENDPOINTS_ORDERS=http://orders:8080
    - ENDPOINTS_CHECKOUT=http://checkout:8080
    - ENDPOINTS_ASSETS=http://assets:8080
    hostname: ui
    build:
      context: ../../src/ui
      dockerfile: ../../images/java17/Dockerfile
      args:
        JAR_PATH: target/ui-0.0.1-SNAPSHOT.jar
    restart: always
    mem_limit: 256m
    cap_drop:
      - ALL

  catalog:
    hostname: catalog
    build:
      context: ../../src/catalog
      dockerfile: Dockerfile
    restart: always
    mem_limit: 128m
    cap_drop:
      - ALL

  carts:
    hostname: carts
    build:
      context: ../../src/cart
      dockerfile: ../../images/java17/Dockerfile
      args:
        JAR_PATH: target/carts-0.0.1-SNAPSHOT.jar
    restart: always
    environment:
      - JAVA_OPTS=-XX:MaxRAMPercentage=75.0 -Djava.security.egd=file:/dev/urandom
      - SERVER_TOMCAT_ACCESSLOG_ENABLED=true
    mem_limit: 256m
    cap_drop:
      - ALL

  orders:
    hostname: orders
    build:
      context: ../../src/orders
      dockerfile: ../../images/java17/Dockerfile
      args:
        JAR_PATH: target/orders-0.0.1-SNAPSHOT.jar
    restart: always
    environment:
      - JAVA_OPTS=-XX:MaxRAMPercentage=75.0 -Djava.security.egd=file:/dev/urandom
      - SERVER_TOMCAT_ACCESSLOG_ENABLED=true
      - SPRING_PROFILES_ACTIVE=activemq
      - SPRING_ACTIVEMQ_BROKERURL=tcp://activemq:61616
    mem_limit: 256m
    cap_drop:
      - ALL
    depends_on:
      - activemq

  checkout:
    build:
      context: ../../src/checkout
      dockerfile: ../../images/nodejs/Dockerfile
    hostname: checkout
    restart: always
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid
    environment:
      - ENDPOINTS_ORDERS=http://orders:8080
    mem_limit: 256m
    cap_drop:
      - ALL
    depends_on:
      - orders

  assets:
    hostname: assets
    environment:
      - PORT=8080
    build:
      context: ../../src/assets
      dockerfile: Dockerfile
    restart: always
    mem_limit: 64m
    cap_drop:
      - ALL

  activemq:
    build:
      context: .
      dockerfile: ../../images/activemq/Dockerfile
    image: watchn/activemq
    hostname: activemq
    restart: always
    ports:
      - "61616:61616"
      - "8161:8161"
    mem_limit: 256m